STEP:         10        #time cycle in milliseconds
PIPE:         plcpipe   #UNIX path of named pipe polled for commands

#hardware
HW:         STDI/O      #just a text tag that appears in a footer

#user space interface:
USPACE: 
    BASE:         50176            #hardware address base
    WR:        4               #write offset
    RD:        0                #read offset


#COMEDI interface:
COMEDI: 
    FILE:     0           #device and subdevice nodes of comedi driver.
    SUBDEV: 
        IN: 0
        OUT: 1
    

#SIMULATION IO
SIM: 
    INPUT:   sim.in
    OUTPUT:  sim.out

#PROGRAM    
DI:
    - 16
    - INDEX: 0
      BYTE:  0	
      BIT:   0
      ID:    A    
    - INDEX: 1
      BYTE:  0
      BIT:   1 
      ID:    B    
    - INDEX: 2
      BYTE:  0
      BIT:   2
      ID:    C        
 
DQ:
    - 16
    - INDEX: 0
      BYTE:  0
      BIT:   0
      ID:    RESULT

TIMERS:
    - 2  
    - INDEX: 1
      RESOLUTION: 10
      PRESET: 10
            

PULSES:
    - 2
 
# triple majority circuit
# https://en.wikipedia.org/wiki/Triple_modular_redundancy
PROGRAM:
    - 2 
    - INDEX: 0
      ID: triple_majority.ld 
